### ISSUE TITLE
System wide cosmetic style changes to React-Admin showcase

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#23]

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 
Bogdan fixed it, could you please check it?

**Comment by PhilBarrett** [comment]
@kuvakina looking closer, thank you. Please see charts though, this looks very different from React showcase.

**Comment by kuvakina** [comment]
@BogdanScherban 
Original Charts looks like this:
![chart](https://user-images.githubusercontent.com/40596171/58346395-774e6800-7e63-11e9-921f-dcfef37fb5a8.png)


Charts on Showcase-devra look this way:
![chart_devra](https://user-images.githubusercontent.com/40596171/58346450-9fd66200-7e63-11e9-8b30-e11825d853cc.png)

**Comment by BogdanScherban** [comment]
Styles fixes, which should be done:
1) Change blocks header to grey
2) Change table header (# , Date, NEWS Score , Source) to green / light green
3) Icons should be in rectangles
4) Sorted column should be highlighted with pale green color
5) Add separate lines for columns
6) Create/Edit buttons should be as rectangle
7) Add sort(up/down)  
8) Should date format be 00-Mon-0000 or we can leave 00-00-0000
9) Add space between plugin header and menu header
10) Table highlight lines

**Comment by tony-shannon** [comment]
which *should be* done or are done?

**Comment by kuvakina** [comment]
@tony-shannon  Here is an update for style fixes:

- [x] Change blocks header to grey
- [x] Change table header (# , Date, NEWS Score , Source) to green / light green
- [x] Icons should be in rectangles
- [x] Sorted column should be highlighted with pale green color
- [x] Add separate lines for columns
- [x] Create/Edit buttons should be as rectangle
- [x] Add sort (up/down)
- [x] Add space between plugin header and menu header
- [x] Table highlight lines
- [x] back button instead of home button in the Topbar
- [x] switchers in Vitals-plugin

- [ ] Should date format be 00-Mon-0000 or we can leave 00-00-0000 ? @tony-shannon @PhilBarrett

**Comment by PhilBarrett** [comment]
@simongamester these are some of the changes being made, but sense there are more required following your review

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

All style issues above, except for "Should date format be 00-Mon-0000 or we can leave 00-00-0000 ?", were done. Could you please check it?

Also should I test and compare all plugins and add differences between dev.r.f and showcase-devra.r.f?

**Comment by PhilBarrett** [comment]
That's fine for now, thanks Alexandra
