### ISSUE TITLE
Medium: Hovering over Dashboard Widget Rows

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#41]
When hovering over the rows within any widgets on the dashboard, no row hover effects are being displayed. It’s convention to invert the colour when hovering over any rows within a panel or widget. The mouse cursor should also change to a pointer (cursor: pointer;)

**Comment by BogdanScherban** [comment]
@simongamester 

Could you please clarify, what do you mean as Dashboard? Which elements of UI should have cursor "pointer"?
Could you please add screenshot?

**Comment by simongamester** [comment]
@BogdanScherban Apologies, I mean Patient Summary. The page were we display widgets...

![Screenshot 2019-05-31 at 10 42 09](https://user-images.githubusercontent.com/8059219/58697075-cf6bf980-8390-11e9-85f7-a6168c5e7850.png)

Cursor 'pointer' should be applied to the table rows within these widgets.

**Comment by BogdanScherban** [comment]
OK! I need in 0.2-0.25 h for this.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett @simongamester 

This was done. Result in the video: https://drive.google.com/file/d/1vKU1fLo-r-xzjAIk1wByTygOFKqJAK-A/view

**Comment by simongamester** [comment]
@BogdanScherban This is caused because the View button doesn't have a white background by default, I think it's transparent. So when you hover over the row, you're seeing a transition on the button between transparent and white, but the row background changes to green immediately.

Also, please could you keep the green border on the View button when not hovering over it. It looks like the View button has no border in it's default state.

![Screenshot 2019-06-03 at 18 09 58](https://user-images.githubusercontent.com/8059219/58820562-d3b34380-862a-11e9-8991-7ab23348effe.png)

**Comment by simongamester** [comment]
@BogdanScherban I've also checked the Patient Summary and the rows within the widgets aren't hovering over in green.

**Comment by BogdanScherban** [comment]
@simongamester 

OK, should I add hovering to Patient Summary panels?
Because I remember that it was done but later we moved it.

**Comment by simongamester** [comment]
The only panels we want to add hovers on the patient summary are the rows within widgets i.e.

![Screenshot 2019-06-04 at 14.07.16.png](https://images.zenhubusercontent.com/5cc737542781b443a5657ce1/3d2ed103-e6d7-42fe-98be-63cd623e30fd)

**Comment by BogdanScherban** [comment]
@simongamester 

This issue has been done
https://drive.google.com/file/d/1yCdO-C18uSCybyg-7MVtZYwMSmPmXmUQ/view

**Comment by simongamester** [comment]
@PhilBarrett Looks good to me. Thanks Bogdan.
