### ISSUE TITLE
Add patient photo into patient banner

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#48]
Need mock up in first instance before moving into dev

See examples from http://healthdesignchallenge.com/ (1st and 3rd prize)

Rounded vs squared also a consideration

**Comment by simongamester** [comment]
I've added the photo into the patient banner. Used this as the source for the sample image - https://randomuser.me/photos

Photo has been updated to all InVision slides in the Showcase prototype for context.

https://invis.io/KPS95C2ZR6X

Here's a sample:

![Screenshot 2019-05-30 at 15 37 52](https://user-images.githubusercontent.com/8059219/58640824-cc6dfc00-82f1-11e9-8f41-9838768a6c6b.png)

**Comment by PhilBarrett** [comment]
Design work signed off, moving back to development now

**Comment by tony-shannon** [comment]
add this to emergency summary view for now
#57

**Comment by BogdanScherban** [comment]
1) Where can we get:
- patient photo (and which format);
- weight
- BMI
2) As I understand correctly, color of Weight and BMI diagram should changed depends on value? In this case I should know principle of color definition
3) Oxygen Saturation, Blood Pressure, Systolic and Diastolic pressure - from the latest Vitals?
4) What is "Lab results"? Is it "Test Results" from the old Showcase?

And the last one, but probably, the most important:

If we want to show photo, weight, BMI, Lab Results and Events - it means, that we should create a tool to add this information?
Isn't it?

Should we create Events and Lab Results plugins before we start new SPV?
And where should we set patient weight and BMI?
______________________________________________________________________________

**Phil:**
1. Weight and BMI please make up for now, i'll find the templates to use 
2. I'll come back to you on this
3.  Yes
4. Yes 

Yellow - Less than 18.5 = Underweight
Green - Between 18.5 - 24.9 = Healthy Weight
Amber- Between 25 - 29.9 = Overweight
Red - Over 30 = Obese

yes I thought results was already in (events new), but clearly not. I'll separate out these in different tasks. you can add placeholders in perhaps in the meantime

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

Part of this issue has been done and I upload my results on Showcase-Devra:
https://drive.google.com/file/d/1sHs4cVtitHJTuoRNhJKd9Nj_jWb-xhFf/view

Few words about results:
1) Switcher between Patient summary panels and Patient Summary roll - done;
2) Patient photo - random, from https://randomuser.me/photos
![Screenshot from 2019-06-21 19-14-31](https://user-images.githubusercontent.com/39263134/59936501-d4384080-9458-11e9-93af-60623c6cc711.png)

3) Patient age is calculated depends on Patient birthdate;
4) Height, Weight and BMI - random values;
5) Oxygen saturation, Blood pressure, Systolic and Diastolic pressure - hardcore constants;
6) Problem/Issues, Medications and Allergies - real data, similar to Patient summary panels;
7) Lab Results - dummy data (because we don't have patients with lab results);
8) Events Timeline - will be done later, when we create Events plugin;
9) Vitals chart - real data, similar to Vitals plugin chart.

Besides this, I created Test Results plugin with dummy data. Why dummy? 
Because:
1) We don't have patients with test results;
2) Test results can't be created/edited by user. Only review.
________________________________________________________________________________

Questions and **problems** about this issue:
1) Which vitals data should be shown here? The latest Vitals? And what should be shown here if we don't have this information?
![Screenshot from 2019-06-21 18-58-42](https://user-images.githubusercontent.com/39263134/59935500-9c2ffe00-9456-11e9-8f48-67ac6e404d55.png)
2) Small problem with Lab Results table. Let's look at JSON response structure:
![Screenshot from 2019-06-21 19-00-52](https://user-images.githubusercontent.com/39263134/59935642-ea450180-9456-11e9-9c40-a9dc67b4ee1a.png)
3) At Showcase-Devra we can't get a patient photo because of Content Security Policy:
![Screenshot from 2019-06-21 19-05-30](https://user-images.githubusercontent.com/39263134/59935954-8f5fda00-9457-11e9-9766-a06905bd2d92.png)
For the same reason Feeds don't work at Showcase-Devra,

Normal range, value with units are items of **testResults** array inside each result. Look at the dummy data structure, it is more understandable:
https://github.com/PulseTile/PulseTile-RA/blob/showcase/src/version/plugins/Results/dummyTestResults.js

Should I show the table by these arrays?

_______________________________________________________________________________

What left:
1) Lab result table - depends on answer at my Question 2;
2) Events timeline;
3) All dummy/hardcore data should be changed to real.
