### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#55]
Creation of Events tile

http://docs.pulsetile.com/react-events.html

And mockups of how to add a react version of timeline.js with the addition of filtering bar for date ranges 

http://world.time.com/2013/12/05/nelson-mandelas-extraordinary-life-an-interactive-timeline/

https://timeline.knightlab.com/#examples

**Comment by PhilBarrett** [comment]
See following for what we're looking to achieve following refinement by Simon 
https://projects.invisionapp.com/d/#/console/17651701/366869277/comments
https://projects.invisionapp.com/d/#/console/17651701/366875604/comments
https://projects.invisionapp.com/d/#/console/17651701/366875603/comments
https://projects.invisionapp.com/d/#/console/17651701/366896562/comments

**Comment by PhilBarrett** [comment]
Estimated 10-12hrs. @tony-shannon to discuss on Monday.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett @DmitrySolyannik 

I solved this issue and upload it to the Showcase-Devra, but it doesn't work correctly on the Showcase-devra because of server settings.

I created timeline with dummy events and customized it according to Simon's mockups:
![Screenshot from 2019-06-26 18-08-25](https://user-images.githubusercontent.com/39263134/60191919-c1997f00-983d-11e9-95e3-a034955c0533.png)

But when I upload my results to the Showcase-Devra - I got following result:
![Screenshot from 2019-06-26 18-12-06](https://user-images.githubusercontent.com/39263134/60192031-ee4d9680-983d-11e9-953e-fab18f291e13.png)

You can see, that vertical orange line is absent, and blocks don't have required margins.

I assumed, that the reason in JSS. To check it, I upload my build to my local QWED (via build, how we worked earlier), but result was normal:
![Screenshot from 2019-06-26 18-14-31](https://user-images.githubusercontent.com/39263134/60192282-47b5c580-983e-11e9-8e7b-decf728b0303.png)

So, the reason is not in JSS.

I found a reason: in Showcase-Devra we have error in console:
![Screenshot from 2019-06-26 18-15-41](https://user-images.githubusercontent.com/39263134/60192406-7633a080-983e-11e9-8f29-f1dbe684f4fa.png)

Timeline tool try to run request:
![Screenshot from 2019-06-26 18-16-37](https://user-images.githubusercontent.com/39263134/60192493-93686f00-983e-11e9-9b87-5b662dfb5931.png)

@DmitrySolyannik said, that the reason in blobs - they should be enabled on Showcase-Devra.

Could we do this?

I can try to create timeline by the other plugin, but:
1) in this case we try additional 3-4 h;
2) we don't have a guarantee, that new plugin will not have the same problem.

**Comment by PhilBarrett** [comment]
To be completed

**Comment by kuvakina** [comment]
Related issue https://github.com/PulseTile/PulseTile-RA/issues/25

**Comment by PhilBarrett** [comment]
Closing here as #25 master
