### ISSUE TITLE
Business intelligence UX/ Population health UX

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#56]
Mock up options required to show at a regional level you could search and display 

Timeline graphs
Hierarchy chart
Bar Charts
Map based charts (by ward)

examples could be

number of people in a geographical ward with a certain condition, filtered by age, sex
number of people on a certain type of medicine
People with a high number of diagnosis (co-morbidities)
Number of people who have had a certain vaccination

https://www.google.com/maps/d/u/0/embed?mid=1njpbeGN5Qu0H4MPZW5ZQBCyEWso&hl=en&ie=UTF8&oe=UTF8&start=0&num=200&msa=0&source=embed&t=h&ll=54.42945382168108%2C-2.8089135156274097&spn=1.549698%2C3.515625&z=8&output=embed

https://d3js.org/
https://www.qgis.org for examples

**Comment by PhilBarrett** [comment]
See https://projects.invisionapp.com/d/main#/console/17676051/366936553/preview from @simongamester . UX work now complete so looking for estimates before work commencing on this development

**Comment by tony-shannon** [comment]
json example should be ;

{
ptID: randomID_AXKU123
Age: 45
Diagnosis: Diabetes
Healthscore: 35
Gender: Male
}

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett @simongamester 

Part of this issue has been done and upload to Showcase-Devra:
https://drive.google.com/file/d/1GahoYWKsbMkOmWte0TXUb-_D-JtNFcDB/view

It is available by the URL: 
https://showcase-devra.ripple.foundation/#/business

Only Heat Map should be done, but I have a Q about it.

I investigated this link: https://www.qgis.org 
Is it necessary to use exactly this tool for map? Because if I understand correctly, it is desctop application, and I didn't found how it can be integrated to web-application...

Can we try to use this NPM?
https://www.npmjs.com/package/google-map-react

It gives possibility to show the map (by center and zoom settings), and add a lot of objects like colored circles etc.

**Comment by simongamester** [comment]
@BogdanScherban I see what you mean about qgis.org. No doubt it was selected because it's open source. I know we've always tried to use open source software in the past so not sure whether using google maps would conflict with this, this may be a question for @tony-shannon or @PhilBarrett I'm afraid.

As you say, Google Maps has an extensive API and specific layers for heat mapping, so would be an ideal choice - https://developers.google.com/maps/documentation/javascript/heatmaplayer

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett @simongamester 

I've completed tins issue and uploaded it to the Showcase-Devra. Result at my local machine:
https://drive.google.com/file/d/17xqottkhTyEI6fo58gXD7t8CSB5_J1cA/view

All data are dummy, but latitude/longitude of the cities - correct, from this source:
https://latitudelongitude.org/gb/pickering

But it doesn't work at Showcase-Devra, because of Content Security Policy:
![Screenshot from 2019-07-02 18-03-31](https://user-images.githubusercontent.com/39263134/60523675-cf467d00-9cf3-11e9-81a2-19c1c596bef0.png)
![Screenshot from 2019-07-02 18-03-55](https://user-images.githubusercontent.com/39263134/60523679-d077aa00-9cf3-11e9-93a4-0f9ab401b6fd.png)

The same reason for Photo, Feeds, Event Timeline etc. - it is necessary to change server settings to provide correct working.

**Comment by tony-shannon** [comment]
Good job 

Still to be done on this ;
 
CORS settings to enable the map
Order of diseases should be Measles, Asthma, Diabetes, Dementia
Pie Charts - update by healthscore doesnt work

Charts should use Dummy Data locally for now , not NodeRed API for now

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

This issue has been done, except CORS:
https://drive.google.com/file/d/1ygoyP-0oCTtHueFcYN6UAcXDlDUa8Q2T/view

Done: Order of diseases should be Measles, Asthma, Diabetes, Dementia
Done: Pie Charts - update by healthscore doesnt work
Done: Charts should use Dummy Data locally for now , not NodeRed API for now

Charts Dummy data similar to NodeRed, but it set on the cleint side.

**Comment by PhilBarrett** [comment]
Thanks @BogdanScherban 

@DmitrySolyannik with you on the NGINX front to enable CORS

**Comment by PhilBarrett** [comment]
After investigation it was found to be NGINX related with the Content-Security-Policy headers measures blocking external traffic. This has been commented out in the NGINX settings and working fine![Screen Shot 2019-07-12 at 14.56.02.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/93394a4d-931b-42d9-9e47-51774f30ba37)
