### ISSUE TITLE
Charts Upgrade

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/Showcase-Project#66]
We are revisiting the Charts for the Showcase and @simongamester  is working on UX improvements

for now we will work on basis of DataSet with 4 key elements

Age
Location (PostCode)
Gender
Diagnosis (Measles/Asthma/Diabetes/Dementia)
Healthscore (1-100)

Will need a dataset with 100-1000 records of this sort to enable chart manipulation at the BI level
Will be deidentified data

Will click through to dummy deidentified MPV view with 3/5/7 patients, perhaps randomly

With toggle to identified MPV view of chosen 3/5/7 good test patients

**Comment by tony-shannon** [comment]
Related wireframes in progress
https://invis.io/WYSC631V6XA#

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I investigated this issue and have a lot of questions about it. Besides this, I prepared my estimation of this task.

**STEP 1 (2-3 h)**

At this step we should create new page (Business Intelligence) with two main elements:
- search parameters block (without form!); 
- main block with right sidebar, which will change main block content (Bar Chart, Pie Chart, Heat Map);
- button Patients which redirect to Patient list;

**Questions:**
1) Should Business Intelligence page be a Homepage in Showcase-devra?
2) Should I change Showcase main color to orange like invisio?
3) As you can see, topbar lower block (which includes menu button and patient banner) is absent in invisio. I mean green block with Menu button. Should we removed it on this page generally?
![Screenshot from 2019-06-10 14-06-13](https://user-images.githubusercontent.com/39263134/59191742-fe504f80-8b88-11e9-9b37-64b6d44fb2ac.png)
![Screenshot from 2019-06-10 14-06-28](https://user-images.githubusercontent.com/39263134/59191750-027c6d00-8b89-11e9-939a-cf31c214ee47.png)
4) I need in this three icons in both modes (checked and inversed). Until I don't have them I can use only labels "Bar Chart", "Pie Chart", "Heat Map"
![Screenshot from 2019-06-10 14-09-11](https://user-images.githubusercontent.com/39263134/59191923-91898500-8b89-11e9-8258-0b23c654a0fb.png)
5) Which behavior should be by click on these icons:
![Screenshot from 2019-06-10 14-11-15](https://user-images.githubusercontent.com/39263134/59191957-a8c87280-8b89-11e9-86ad-a091b3588034.png)
If nothing, should we add them generally?

**STEP 2 (3-4 h)**

1) Create searching form in Business Intelligence block. Form data should saved in Store;
2) Create Grids in the main block with labels "Place for map", "Place for N-chart" etc.

**Questions:**
1) As I understand correctly, "Health Score" is a numberic value from 0 till 100. Am I right?
![Screenshot from 2019-06-10 14-22-23](https://user-images.githubusercontent.com/39263134/59192497-4d977f80-8b8b-11e9-832d-8f2480f21f97.png)
![Screenshot from 2019-06-10 14-22-12](https://user-images.githubusercontent.com/39263134/59192484-453f4480-8b8b-11e9-8675-41b11a00f977.png)

In this case, can we use following ranges: 
0-33: poor
34-66: good
67-100: very good

**STEP 3 (5-6 h)**

1) Create dummy data;
2) Create functionality to calculate data for Bar Charts;
3) Build Bar Charts

**Questions:**
1) Which actions should be provide by clicking on chart legend or clicking/hovering on chart bar?
![Screenshot from 2019-06-10 14-26-38](https://user-images.githubusercontent.com/39263134/59192632-c991c780-8b8b-11e9-8ab7-ba4e1a4cd156.png)

**STEP 4 (6-8 h):**

1) Create functionality to calculate data for Diagnosis by Gender Charts;
2) Build these charts 

**Questions:**
Let's look at this diagrams:
![Screenshot from 2019-06-10 14-27-22](https://user-images.githubusercontent.com/39263134/59192659-e3cba580-8b8b-11e9-8a44-181944ceae72.png)

1) Male/Female - depends on, which gender more for this diagnosis?
2) "130", "98", "130", "39": total number of patients for this diagnosis?
3) 62%, 41%, 76%, 23% - ratio (number of patients with this diagnosis) / (total number of patients)?
4) Which actions should be provide by clicking on chart legend or clicking/hovering on diagrams?

**STEP 5 (6-8 h):**

1) Create chart "Average health Score"
2) Create population chart;
3) Calculate data for chart Average health Score vs Age
4) Create this chart

**Questions:**
1) Is "Average health Score" a average value for all patients, which was found by the search parameters?
2) Where can I found data for Population chart? It isn't dummy patients, we should create separate request for it. Can we use data from invisio example?
3) Is localization like "Yorkshire, UK" - constant? User can't search other localization?
4) As I understand correctly each bar in "Average health Score vs Age" is calculated as average value for current age group (0-10, 11-20 etc.)?
5) Color of Bar depends on average value (green - very good, yellow - good etc.)?

**STEP 6 (6-8 h):**

Create map. I estimated this step so much because we didn't work with this tool earlier and I don't know, how to do this.

**Comment by simongamester** [comment]
@BogdanScherban A few answers to some of your questions.

### Step 1

4. Here are the icons:
https://drive.google.com/file/d/1fsgcUBkMA4bdZHtKRAAd6VgqbzOffBmm/view?usp=sharing

5. This icon at the top (Orange on white background) shows that the the filter form is in an expanded state. When the user clicks this icon, the filter form (By Age, Health Score, Diagnosis etc) will collapse and the icon will revert to white on black. this is a similar behaviour to expanding / collapsing the search for a table listing.

### Step 3

1. When the user hovers over a bar on the chart, display values for all diagnostics within the selected bar. I don't think there would be any click behaviour but will defer to @tony-shannon on this.

### Step 4

1. I'm going to update this one shortly and use a new pie chart. Will respond once this has been updated.

### Step 5

1. This is due to change to a line chart similar to the one above. Data will be slightly different so please ignore for now.
4. Same as above.
5. Same as above.

**Comment by PhilBarrett** [comment]
https://projects.invisionapp.com/d/main#/console/17676051/366936553/
Estimation on this screen only required at this stage, using mock data

**Comment by PhilBarrett** [comment]
Linked with #56

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

Today I created all charts, except map. Unfortunately, I can't prepare the video (because free videos per month are finished), but you can see results on the screenshots:

![Screenshot from 2019-06-27 17-44-49](https://user-images.githubusercontent.com/39263134/60275956-5ade9900-9903-11e9-91f7-2adc53bfa1bb.png)
![Screenshot from 2019-06-27 17-45-02](https://user-images.githubusercontent.com/39263134/60275958-5b772f80-9903-11e9-998d-d03be23cc906.png)
![Screenshot from 2019-06-27 17-45-17](https://user-images.githubusercontent.com/39263134/60275959-5b772f80-9903-11e9-8d8d-e36260f2bd90.png)

All charts use dummy data.

The next stages are form and Map adding.

@simongamester 
Simon, could you please give me icon for Pie Charts in non-selected mode. This icon is absent in this storage:
https://drive.google.com/file/d/1fsgcUBkMA4bdZHtKRAAd6VgqbzOffBmm/view?usp=sharing

On Monday I'm going to continue this issue.

**Comment by PhilBarrett** [comment]
Closing this as connected to #56
