### ISSUE TITLE
Charts refinement

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/Showcase-Project#78]
- Text typeface is inconsistent
 - Spacing at bottom, spacing inbetween bars (see showcase.r.f)
 - Not responsive 
 - Can’t click from charts to MPV

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I need in 1-1.5 h for these items:
> Text typeface is inconsistent
> Spacing at bottom, spacing inbetween bars (see showcase.r.f)
> Not responsive 

But could you please clarify this moment:
> Can’t click from charts to MPV

Now click on the Bar redirect us to the patient list. But it is empty, because we don't have possibility to get patients by age or by Neighbourhood / Hospital / Mental Health etc.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

I'm working on #78, and following items were done and upload to this moment:
> Text typeface is inconsistent
> Spacing at bottom, spacing inbetween bars (see showcase.r.f)
> Can’t click from charts to MPV

The last issue isn't work on Showcase-Devra because QWED should be updated. For  this reason I show local result:
https://drive.google.com/file/d/1RscV25f7g1q3C4t0Klo_qjefkYDY9so-/view
_______________________________________________________________________________

But I have one problem, which should be discussed.

Charts are built with dummy data, because we don't have request for total patients array.
MPV list is built with real data.

For this reason we can see consistence with statistic:
6 patients 0-30 years old by Chart (dummy data),
2 patients 0-30 years old by MPV (real data)

We can't mix dummy and real data for MPV. We can use only one type of data here.

For this reason I suggest to create a request for total patients array, like it was done at old Showcase. In this case I can parse result and create charts with real data, and consistence will be removed.

**Comment by PhilBarrett** [comment]
I like the sound of that Bogdan, good suggestion, thank you.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

Responsive issue also done:
https://drive.google.com/file/d/15ZpM3B8ZMET7ntMOp0F0cMk4yAfjyLMb/view

**Comment by PhilBarrett** [comment]
Reviewed and closing
